# This is a basic workflow to help you get started with Actions
name: EUxxxx
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  push:
#    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  schedule:
    # UTC (国内 UTC+8)
    - cron: '15 4 * * 1,3,5'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # 超时设置
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: Setup Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "Shanghai Standard Time"
        
      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}   # replace this with your own repository such as >> owner/repo
          older-than-seconds: 172800          # remove all workflow runs older than 1 day >> 24*60*60=86400
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup FFmpeg using versions
        uses: Iamshankhadeep/setup-ffmpeg@v1.2
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Setup Environment
        run: |
          pip install --upgrade pip
          pip install Pillow pyscreenshot
          pip install -r ./requirements.txt
          
      - name: 'Renew'
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          MAILPARSER: ${{ secrets.MAILPARSER }}
          BARK_TOKEN: ${{ secrets.BARK_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
        run: |  
          xvfb-run python3 ./main.py
